/*
  Practica 2 - Pipelines CI/CD en Jenkins con Docker y Groovy
*/

// ==========================
// Practica 2 - Ejercicio 4
// ==========================
def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()  
    }
}

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  environment {
    // IMAGE_NAME (tag para docker build)
	  IMAGE_NAME = "myapp:${env.GIT_COMMIT}"
  }

  stages {

    // ==========================
    // Practica 2 - Ejercicio 1
    // ==========================
    stage('Info') {
      steps {
        // Imprime JOB_NAME y BUILD_NUMBER
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    // ==========================
    // Practica 2 - Ejercicio 3
    // ==========================
    stage('Build CI Image') {
      steps {
        script {
          // Construir imagen CI para ejecutar 'make link' y 'make test'
          // Nombre: 'python-imagen-ci'
          docker.build('python-imagen-ci', '-f devops/ci.Dockerfile .')
        }
      }
    }

  // ==========================
  // Practica 2 - Ejercicio 3-4
  // ==========================
  stage('Lint') {
	  steps {
		  runInDocker('python-imagen-ci') {
			  // Instala dependencias del proyecto + herramientas de revisión de reglas de estilo y tipos de datos
			  sh 'pip install -r requirements.txt flake8 mypy'
			  sh 'make lint'
		  }
	  }
	}

  // ==========================
  // Practica 2 - Ejercicio 3-4
  // ==========================
	stage('Test') {
	  steps {
		  runInDocker('python-imagen-ci') {
			  sh 'pip install -r requirements.txt flake8 mypy pytest'
			  sh 'pytest -q'
			  sh 'make test'
		  }
	  }
  }

  // =========================
  // Practica 2 - Ejercicio 5
  // =========================
  stage('Build image') {
    steps {
      script {
        // Construye la imagen Docker usando el Dockerfile del repo
        // IMAGE_NAME -> Se define en las variables
        echo "Tag imagen: ${env.IMAGE_TAG}"
        docker.build(env.IMAGE_NAME, "-f devops/Dockerfile .")
      }
    }
  }
  
  }
}
