/*
  Practica 2 - Pipelines CI/CD en Jenkins con Docker y Groovy
*/

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {

    // ==========================
    // Practica 2 - Ejercicio 1
    // ==========================
    stage('Info') {
      steps {
        // Imprime JOB_NAME y BUILD_NUMBER
        sh 'echo "Job: ${env.JOB_NAME}"'
        sh 'echo "Build: ${env.BUILD_NUMBER}"'
      }
    }
    
  }
}
