name: "CI/CD"

# Practica 3 - Ejercicio 3 - 7
# Variables de entorno a nivel de workflow
env:
  IMAGE_NAME: my-app
  APP_URL: myapp
  IMAGE_REPO: Nieves-16/devops-training-python-app

# Practica 3 - Ejercicio 1 - 4
# Eventos que disparan el workflow
on:
  # Se ejecuta en todas las ramas
  push:
    branches: ['**']

  # Se ejecuta al crear PR con destino develop y master
  pull_request:
    branches: [develop, master]

  # Permite ejecutar el workflow manualmente con un input booleano RUN_CD (default false)
  workflow_dispatch:
    inputs:
      RUN_CD:
        description: "Run CD stage"
        required: false
        default: false
        type: boolean

      # Ejecucion manual con parametros
      DEPLOY_ENV:
        description: "Run environment"
        required: false
        type: choice
        options:
          - DEV
          - PRO

# Practica 3 - Ejercicio 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9
# Definicion de jobs
jobs:
  # Job CI
  ci:
    environment: ${{ github.ref_name == 'master' && 'PRO' || 'DEV' }}
    runs-on: ubuntu-latest

    env:
      APP_URL: myappurl

    # Pasos
    steps:

      # Clona el repositorio en el runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Imprimir información del entorno
      - name: Info
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Name: ${{ runner.name }}"

      # Imprimir variables
      - name: Variables
        run: |
          echo "IMAGE_NAME=${IMAGE_REPO}:$(cat VERSION)" >> $GITHUB_ENV
          echo "APP_URL: ${{ env.APP_URL }}"
          echo "REGISTRY_HOST: ${{ vars.REGISTRY_HOST }}"

      # Imprimir parámetros
      - name: Imprimir parámetros
        run: |
          echo "RUN_CD value: ${{ inputs.RUN_CD }}"
          echo "DEPLOY_ENV value: ${{ inputs.DEPLOY_ENV }}"

      # Build CI image
      - name: Build CI image
        run: docker build -t python-imagen-ci -f devops/ci.Dockerfile .

      # Lint
      - name: Lint
        run: |
          docker run --rm -v "${GITHUB_WORKSPACE}:/app" -w /app python-imagen-ci bash -c "\
            pip install -r requirements.txt flake8 mypy && \
            make lint"

      # Test
      - name: Test
        run: |
          docker run --rm -v "${GITHUB_WORKSPACE}:/app" -w /app python-imagen-ci bash -c "\
            pip install -r requirements.txt flake8 mypy pytest && \
            pytest -q && \
            make test"

      # Build image
      - name: Build image
        run: docker build -t $IMAGE_NAME -f devops/Dockerfile .

  # Job CD
  cd:
    needs: ci
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.RUN_CD == true || github.ref_name == 'develop' || github.ref_name == 'master' }}
    environment: ${{ github.ref_name == 'master' && 'PRO' || 'DEV' }}
    runs-on: ubuntu-latest

    # Pasos
    steps:
      - uses: actions/checkout@v4
      - name: CD
        run: |
            echo "CD habilitado: RUN_CD=${{ github.event.inputs.RUN_CD }}, branch=${GITHUB_REF_NAME}"

      # Despliegue
      - name: Despliegue - espera - logs
        run: |
          docker compose up -d
          sleep 5
          docker compose logs app

      # Limpieza (aunque falle)
      - name: Cleanup
        if: always()
        run: |
          docker compose down --volumes
          docker rmi $IMAGE_NAME || true
